// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4s_GVqbL33R5BVJqngOaT8ljv9ocrnk4',
    appId: '1:26457768453:web:4f0d1328946b43d269526c',
    messagingSenderId: '26457768453',
    projectId: 'touchorder-2c908',
    authDomain: 'touchorder-2c908.firebaseapp.com',
    storageBucket: 'touchorder-2c908.appspot.com',
    measurementId: 'G-5V4N5ZDPZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs1mbgwVygMlF9_hU3jSlSTpFqTrJo6zA',
    appId: '1:26457768453:android:64b4182015f663f869526c',
    messagingSenderId: '26457768453',
    projectId: 'touchorder-2c908',
    storageBucket: 'touchorder-2c908.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrz1X4aOG_pmJbvjtSx8Tq1uH2A7ErWj4',
    appId: '1:26457768453:ios:72721dfcf4ce51c569526c',
    messagingSenderId: '26457768453',
    projectId: 'touchorder-2c908',
    storageBucket: 'touchorder-2c908.appspot.com',
    iosBundleId: 'com.example.touchOrder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrz1X4aOG_pmJbvjtSx8Tq1uH2A7ErWj4',
    appId: '1:26457768453:ios:3a8583440692dfa569526c',
    messagingSenderId: '26457768453',
    projectId: 'touchorder-2c908',
    storageBucket: 'touchorder-2c908.appspot.com',
    iosBundleId: 'com.example.touchOrder.RunnerTests',
  );
}
